# the notation for the synaptic parameters is as follows:
# B blocker, C collector, S spike source,
# w weight, d delay,
# a one's own, z other,
# i inhibition, e excitation
# If B stands before C than the connection is from B to C.
# Example: dSaB would mean a delay from a spike source to the homolateral blocker neuron, and
# wSzB would be the weight from a spike source to the heterolateral blocker neuron.


neuron:
  tau_E: 2.0
  tau_I: 2.0
  tau_mem: 2.07
  v_reset_collector: -90.0

# all inhibitory parameters should be negative real numbers
synapse:
  wSC: 9.0
  dSC: 0.2
  wCCi: -18.0     # uniqueness constraint inhibition
  dCCi: 0.2
  wCCe: 1.8       # continuity constraint excitation
  dCCe: 0.2
  wCCo: -9.0       # ordering constraint inhibition
  dCCo: 0.2

topology:
  add_gating: False
  add_continuity_constraint: False
  add_uniqueness_constraint: False
  add_ordering_constraint: False
  radius_continuity: 1                # continuity constraint range radius
  radius_ordering: 1                  # ordering constraint range radius
